name: sharedtheme_example_mobile
description: Example use of shared_theme_flutter for mobile
version: 1.0.0
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/shared_theme/tree/master/example/packages/mobile

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  sharedtheme_example:
    path: ../base
  shared_theme_flutter: ^0.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Even though these are defined in `package:sharedtheme_example/themes.dart`,
  # They currently have to be duplicated here manually.
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/sharedtheme_example/assets/fonts/Ubuntu-Regular.ttf
        - asset: packages/sharedtheme_example/assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: packages/sharedtheme_example/assets/fonts/Ubuntu-Light.ttf
          weight: 300
    - family: Open Sans
      fonts:
        - asset: packages/sharedtheme_example/assets/fonts/OpenSans-Regular.ttf
        - asset: packages/sharedtheme_example/assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: packages/sharedtheme_example/assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: packages/sharedtheme_example/assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: packages/sharedtheme_example/assets/fonts/OpenSans-SemiBold.ttf
          weight: 500