name: shared_theme
description: Easily share a theme between Flutter and the web.
version: 0.1.0
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/shared_theme

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.2

environment:
  sdk: ">=2.0.0 <3.0.0"