name: shared_theme
description: Share a theme between Flutter and Web.
version: 0.0.1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/shared_theme

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.2

environment:
  sdk: ">=2.0.0 <3.0.0"