name: sharedtheme_example
description: Example base package that uses shared_theme
version: 1.0.0
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/shared_theme/tree/master/example/packages/base

dependencies:
  shared_theme: any
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.2

environment:
  sdk: ">=2.0.0 <3.0.0"