name: sharedtheme_example
description: Example base package that uses shared_theme
version: 0.0.1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/shared_theme

dependencies:
  shared_theme:
    path: ../../../
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.2

environment:
  sdk: ">=2.0.0 <3.0.0"